// Generated by CoffeeScript 1.6.0
(function() {
  var Divider, DividerFactory;

  console.log('Init');

  Divider = (function() {

    Divider.dividers = [];

    Divider.width = 10;

    function Divider() {
      Divider.dividers.push(this);
    }

    return Divider;

  })();

  DividerFactory = (function() {

    function DividerFactory() {}

    DividerFactory.addDivider = function() {
      return new Divider();
    };

    return DividerFactory;

  })();

  DividerFactory.addDivider();

}).call(this);
