// Generated by CoffeeScript 1.6.0
(function() {
  var Divider, DividerFactory, Label, LabelFactory,
    _this = this;

  console.log('Init');

  Label = (function() {

    Label.width = 100;

    Label.labels = [];

    function Label() {
      var label_html;
      console.log('New label');
      Label.labels.push(this);
      label_html = jQuery('<input type="textfield" value="activity"/>');
      jQuery('#label_bar').append(label_html);
      Label.labels.unshift(label_html);
      Label.updateAll();
    }

    Label.updateAll = function() {};

    return Label;

  })();

  Divider = (function() {

    Divider.dividers = [];

    Divider.width = 10;

    function Divider() {
      console.log('New divider');
      Divider.dividers.push(this);
    }

    return Divider;

  })();

  LabelFactory = (function() {

    function LabelFactory() {}

    LabelFactory.addLabel = function() {
      return new Label();
    };

    return LabelFactory;

  })();

  DividerFactory = (function() {

    function DividerFactory() {}

    DividerFactory.addDivider = function() {
      return new Divider();
    };

    return DividerFactory;

  })();

  jQuery(function() {
    return LabelFactory.addLabel();
  });

}).call(this);
